// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieSearch.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieSearch.Api.Data.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieSearch.Api.Domain.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("Actors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Keanu Reeves"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laurence Fishburne"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Carrie-Anne Moss"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Joseph Gordon-Levitt"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Christian Bale"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Heath Ledger"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Morgan Freeman"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tom Hanks"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Robin Wright"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sigourney Weaver"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tom Skerritt"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Amy Poehler"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Phyllis Smith"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sandra Bullock"
                        });
                });

            modelBuilder.Entity("MovieSearch.Api.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("MovieSearch.Api.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("Title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A hacker discovers that reality is a simulation and joins a rebellion against its controllers.",
                            GenreId = 1,
                            ReleaseDate = new DateOnly(1999, 3, 31),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Neo and his allies race to protect Zion while uncovering new truths about the Matrix.",
                            GenreId = 1,
                            ReleaseDate = new DateOnly(2003, 5, 15),
                            Title = "The Matrix Reloaded"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A skilled extractor is offered a chance to erase his past by planting an idea in a target's mind.",
                            GenreId = 2,
                            ReleaseDate = new DateOnly(2010, 7, 16),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Batman faces a criminal mastermind who pushes Gotham and its heroes toward chaos.",
                            GenreId = 1,
                            ReleaseDate = new DateOnly(2008, 7, 18),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A kindhearted man witnesses defining moments in American history while pursuing his childhood love.",
                            GenreId = 3,
                            ReleaseDate = new DateOnly(1994, 7, 6),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A deep-space crew encounters a lethal organism aboard its commercial starship.",
                            GenreId = 2,
                            ReleaseDate = new DateOnly(1979, 5, 25),
                            Title = "Alien"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A retired assassin returns to the criminal underworld after a devastating personal loss.",
                            GenreId = 1,
                            ReleaseDate = new DateOnly(2014, 10, 24),
                            Title = "John Wick"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The emotions inside a young girl's mind struggle to guide her through a major life change.",
                            GenreId = 4,
                            ReleaseDate = new DateOnly(2015, 6, 19),
                            Title = "Inside Out"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A police officer must keep a city bus moving above a set speed to prevent a bomb from exploding.",
                            GenreId = 5,
                            ReleaseDate = new DateOnly(1994, 6, 10),
                            Title = "Speed"
                        });
                });

            modelBuilder.Entity("MovieSearch.Api.Domain.Entities.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors", (string)null);

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 11
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 12
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 13
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 14
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 15
                        });
                });

            modelBuilder.Entity("MovieSearch.Api.Domain.Entities.Movie", b =>
                {
                    b.HasOne("MovieSearch.Api.Domain.Entities.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MovieSearch.Api.Domain.Entities.MovieActor", b =>
                {
                    b.HasOne("MovieSearch.Api.Domain.Entities.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieSearch.Api.Domain.Entities.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieSearch.Api.Domain.Entities.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("MovieSearch.Api.Domain.Entities.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieSearch.Api.Domain.Entities.Movie", b =>
                {
                    b.Navigation("MovieActors");
                });
#pragma warning restore 612, 618
        }
    }
}
